import Button from "./Button";
const ModalPoliticas = ({ isOpen, onClose }) => {
  return (
    <div className={`z-50 fixed inset-0 bg-gray-900 bg-opacity-75 flex justify-center items-center ${isOpen ? 'block' : 'hidden'}`}>
      <div className="bg-n-8/90 rounded-lg shadow-lg p-10 mx-6 lg:w-1/2 mb-5">
        <h2 className="text-lg font-bold mb-8">Políticas de Privacidade</h2>
        <div className="h-80 overflow-y-auto">
          <p className="text-gray-600">A sua privacidade é importante para nós. É política do HamandoUniverso respeitar a sua privacidade em relação a qualquer informação que possamos coletar no site HamandoUniverso, e outros sites que possuímos e operamos.Solicitamos informações pessoais apenas quando realmente precisamos delas para lhe fornecer um serviço. </p>
          <p className="text-gray-600">Fazemo-lo por meios justos e legais, com o seu conhecimento e consentimento. Também informamos por que os coletamos e como será usado. Apenas retemos as informações coletadas pelo tempo necessário para fornecer o serviço solicitado. Quando armazenamos dados, protegemos dentro de meios comercialmente aceitáveis ​​para evitar perdas e roubos, bem como acesso, divulgação, cópia, uso ou modificação não autorizados. </p>
          <p className="text-gray-600">Não compartilhamos informações de identificação pessoal publicamente ou com terceiros, exceto quando exigido por lei. O nosso site pode ter links para sites externos que não são operados por nós. Esteja ciente de que não temos controle sobre o conteúdo e práticas desses sites e não podemos aceitar responsabilidade por suas respectivas políticas de privacidade. Você é livre para recusar a nossa solicitação de informações pessoais, entendendo que talvez não possamos fornecer alguns dos serviços desejados. </p>
          <p className="text-gray-600">O uso continuado de nosso site será considerado como aceitação de nossas práticas em torno de privacidade e informações pessoais. Se tiver alguma dúvida sobre como lidamos com dados do usuário e informações pessoais, entre em contacto connosco. O serviço Google AdSense que usamos para veicular publicidade usa um cookie DoubleClick para veicular anúncios mais relevantes em toda a Web e limitar o número de vezes que um determinado anúncio é-lhe exibido. Para mais informações sobre o Google AdSense, consulte as FAQs oficiais sobre privacidade do Google AdSense. </p>
          <p className="text-gray-600">Utilizamos anúncios para compensar os custos de funcionamento deste site e fornecer financiamento para futuros desenvolvimentos. Os cookies de publicidade comportamental usados ​​por este site foram projetados para garantir que você forneça os anúncios mais relevantes sempre que possível, rastreando anonimamente seus interesses e apresentando coisas semelhantes que possam ser do seu interesse. Vários parceiros anunciam em nosso nome e os cookies de rastreamento de afiliados simplesmente nos permitem ver se nossos clientes acessaram o site através de um dos sites de nossos parceiros, para que possamos creditá-los adequadamente e, quando aplicável, permitir que os nossos parceiros afiliados ofereçam qualquer promoção que pode fornecê-lo para fazer uma compra.</p>
          <p className="text-gray-600"> Compromisso do Usuário: O usuário compromete-se a fazer uso adequado dos conteúdos e da informação que HamandoUniverso oferece no site e com caráter enunciativo, mas não limitativo: A) Não se envolver em atividades que sejam ilegais ou contrárias à boa fé a à ordem pública; B) Não difundir propaganda ou conteúdo de natureza racista, xenofóbica, bbebbet ou azar, qualquer tipo de pornografia ilegal, de apologia ao terrorismo ou contra os direitos humanos; C) Não causar danos aos sistemas físicos (hardwares) e lógicos (softwares) do HamandoUniverso, de seus fornecedores ou terceiros, para introduzir ou disseminar vírus informáticos ou quaisquer outros sistemas de hardware ou software que sejam capazes de causar danos anteriormente mencionados. Mais informações: Esperemos que esteja esclarecido e, como mencionado anteriormente, se houver algo que não tem certeza se precisa ou não, geralmente é mais seguro deixar os cookies ativados, caso interaja com um dos recursos que usa em nosso site.</p>
        </div>
        <Button className="mt-10" onClick={onClose}>Fechar</Button>
      </div>
    </div>
  );
};

export default ModalPoliticas;