import Button from "./Button";
const ModalTermos = ({ isOpen, onClose }) => {
  return (
    <div className={`z-50 fixed inset-0 bg-gray-900 bg-opacity-75 flex justify-center items-center ${isOpen ? 'block' : 'hidden'}`}>
      <div className="bg-n-8/90 rounded-lg shadow-lg p-10 mx-6 lg:w-1/2 mb-5">
        <h2 className="text-lg font-bold mb-8">Termos e Condições</h2>
        <div className="h-80 overflow-y-auto">
          <p className="text-gray-600"><b>1 - Termos:</b> Ao acessar ao site HamandoUniverso, concorda em cumprir estes termos de serviço, todas as leis e regulamentos aplicáveise concorda que é responsável pelo cumprimento de todas as leis locais aplicáveis. Se não concordar com algum desses termos, está proibido de usar ou acessar este site. Os materiais contidos neste site são protegidos pelas leis de direitos autorais e marcas comerciais aplicáveis.</p>
          <p className="text-gray-600"><b>2 - Uso de Licença:</b> É concedida permissão para baixar temporariamente uma cópia dos materiais (informações ou software) no site HamandoUniverso , apenas para visualização transitória pessoal e não comercial. Esta é a concessão de uma licença, não uma transferência de título e, sob esta licença, você não pode: modificar ou copiar os materiais; usar os materiais para qualquer finalidade comercial ou para exibição pública (comercial ou não comercial); tentar descompilar ou fazer engenharia reversa de qualquer software contido no site HamandoUniverso; remover quaisquer direitos autorais ou outras notações de propriedade dos materiais; ou transferir os materiais para outra pessoa ou espelhar os materiais em qualquer outro servidor.Esta licença será automaticamente rescindida se violar alguma dessas restrições e poderá ser rescindida por HamandoUniverso a qualquer momento. Ao encerrar a visualização desses materiais ou após o término desta licença, deve apagar todos os materiais baixados em sua posse, seja em formato eletrónico ou impresso.</p>
          <p className="text-gray-600"><b>3 - Isenção de responsabilidade:</b> Os materiais no site da HamandoUniverso são fornecidos como estão. HamandoUniverso não oferece garantias, expressas ou implícitas, e, por este meio, isenta e nega todas as outras garantias, incluindo, sem limitação, garantias implícitas ou condições de comercialização, adequação a um fim específico ou não violação de propriedade intelectual ou outra violação de direitos. Além disso, HamandoUniverso não garante ou faz qualquer representação relativa à precisão, aos resultados prováveis ou à confiabilidade do uso dos materiais em seu site ou de outra forma relacionado a esses materiais ou em sites vinculados a este site.</p>
          <p className="text-gray-600"><b>4 - Limitações:</b> Em caso algum HamandoUniverso ou seus fornecedores serão responsáveis por quaisquer danos (incluindo, sem limitação, danos por perda de dados ou lucro ou devido a interrupção dos negócios) decorrentes do uso ou da incapacidade de usar os materiais em HamandoUniverso, mesmo que HamandoUniverso ou um representante autorizado da HamandoUniverso tenha sido notificado oralmente ou por escrito da possibilidade de tais danos. Como algumas jurisdições não permitem limitações em garantias implícitas, ou limitações de responsabilidade por danos consequentes ou incidentais, essas limitações podem não se aplicar a si.</p>
          <p className="text-gray-600"><b>5 - Precisão dos materiais:</b> Os materiais exibidos no site HamandoUniverso podem incluir erros técnicos, tipográficos ou fotográficos. HamandoUniverso não garante que qualquer material em seu site seja preciso, completo ou atual. HamandoUniverso pode fazer alterações nos materiais contidos em seu site a qualquer momento, sem aviso prévio. No entanto, HamandoUniverso não se compromete a atualizar os materiais.</p>
          <p className="text-gray-600"><b>6 - Links:</b> HamandoUniverso não analisou todos os sites vinculados ao seu site e não é responsável pelo conteúdo de nenhum site vinculado. A inclusão de qualquer link não implica endosso por HamandoUniverso do site. O uso de qualquer site vinculado é por conta e risco do usuário. Modificações: HamandoUniverso pode revisar estes termos de serviço do site a qualquer momento, sem aviso prévio. Ao usar este site, você concorda em ficar vinculado à versão atual desses termos de serviço.</p>
          <p className="text-gray-600"><b>7 - Lei aplicável:</b> Estes termos e condições são regidos e interpretados de acordo com as leis do HamandoUniverso e você submete-se irrevogavelmente à jurisdição exclusiva dos tribunais naquela localidade.</p>
        </div>
        <Button className="mt-10" onClick={onClose}>Fechar</Button>
      </div>
    </div>
  );
};

export default ModalTermos;